from reportlab.lib import colors
from reportlab.lib.units import mm

# Typography
HEADING_SIZE = 14
TEXT_SIZE    = 12
NAME_SIZE    = 18
NAME_GAP     = 10  # mm

# Left column style
LEFT_TEXT_FONT      = "Helvetica"
LEFT_TEXT_FONT_BOLD = "Helvetica-Bold"
LEFT_TEXT_IS_BOLD   = True

# Spacing
LEADING_BODY     = 12
LEADING_BODY_RTL = 20
GAP_AFTER_HEADING    = 10
GAP_BETWEEN_PARAS    = 10
GAP_BETWEEN_SECTIONS = 12

# Colors
LEFT_BG        = colors.HexColor("#F7F8FA")
LEFT_BORDER    = colors.HexColor("#E3E6EA")
HEADING_COLOR  = colors.black
SUBHEAD_COLOR  = colors.HexColor("#0B7285")
MUTED          = colors.HexColor("#6C757D")
RULE_COLOR     = colors.HexColor("#D7DBE0")
EDU_TITLE_COLOR = SUBHEAD_COLOR

# Card
CARD_RADIUS = 6
CARD_PAD    = 6 * mm

# Icons row
ICON_SIZE    = 6 * mm
ICON_PAD_X   = 4
ICON_TEXT_DY = -5
ICON_VALIGN  = "middle"

# Left inner
LEFT_TEXT_SIZE = 12
LEFT_LINE_GAP  = 16

# Left extra sections
LEFT_SEC_HEADING_SIZE      = 14
LEFT_SEC_TEXT_SIZE         = 12
LEFT_SEC_TITLE_TOP_GAP     = 6
LEFT_SEC_TITLE_BOTTOM_GAP  = 6
LEFT_SEC_RULE_COLOR        = RULE_COLOR
LEFT_SEC_RULE_WIDTH        = 1
LEFT_SEC_RULE_TO_LIST_GAP  = 15
LEFT_SEC_LINE_GAP          = 20
LEFT_SEC_BULLET_RADIUS     = 1.2
LEFT_SEC_BULLET_X_OFFSET   = 2.5
LEFT_SEC_TEXT_X_OFFSET     = 8
LEFT_SEC_SECTION_GAP       = 2
LEFT_AFTER_CONTACT_GAP     = 10
LEFT_SEC_TITLE_ALIGN       = "left"  # left|center|right

# Right extra sections
RIGHT_SEC_HEADING_SIZE       = HEADING_SIZE
RIGHT_SEC_TEXT_SIZE          = TEXT_SIZE
RIGHT_SEC_TITLE_TO_RULE_GAP  = 10
RIGHT_SEC_RULE_COLOR         = RULE_COLOR
RIGHT_SEC_RULE_WIDTH         = 0.8
RIGHT_SEC_RULE_TO_TEXT_GAP   = 14
RIGHT_SEC_LINE_GAP           = 12
RIGHT_SEC_SECTION_GAP        = GAP_BETWEEN_SECTIONS
RIGHT_SEC_PARA_GAP           = 4

# Projects
PROJECT_TITLE_SIZE        = TEXT_SIZE + 1
PROJECT_TITLE_GAP_BELOW   = 14
PROJECT_DESC_LEADING      = 14
PROJECT_DESC_PARA_GAP     = 2
PROJECT_LINK_TEXT_SIZE    = TEXT_SIZE - 1
PROJECT_LINK_GAP_ABOVE    = -10
PROJECT_BLOCK_GAP         = 24

# Education
EDU_TEXT_LEADING = 12

# LinkedIn redirect (اختياري)
LINKEDIN_REDIRECT_URL = "https://tamer.dev/in"
USE_LINKEDIN_REDIRECT = False
USE_MOBILE_LINKEDIN   = False
